version: '3.7'
services:
  postgresql:
    image: postgres:bullseye
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=appl
      - POSTGRES_PASSWORD=1111